# Gov.uk-specific settings
[sources.gov_uk_vehicle_data]
# Direct CSV links for the Gov.uk vehicle statistics
GB_REGISTRATIONS_URL = "https://assets.publishing.service.gov.uk/media/66f15d48bd3aced9da489bdf/df_VEH0160_GB.csv"
UK_REGISTRATIONS_URL = "https://assets.publishing.service.gov.uk/media/66f15d6a7aeb85342827abdc/df_VEH0160_UK.csv"

# Default year for data extraction (can be overridden in function call)
default_year = 2024
# Default table type for data extraction (can be overridden in function call)
default_table_type = "govuk"

# Pipeline settings
[pipeline]
# Default pipeline settings
name = "vehicle_data_pipeline"
destination = "bigquery"
dataset_name = "BQ_DATASET"

# BigQuery destination settings
[destination.bigquery]
location = "GCS_LOCATION"

[runtime]
bigquery_job_location = "GCS_LOCATION"

[gstorage_pipeline_name.sources.filesystem]
bucket_url="BUCKET_URL"