version: 2

sources:
  - name: raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET', 'vehicle_data') }}"
    tables:
      - name: gov_uk_vehicle_data
        description: "Raw vehicle licensing data from the UK Government"
        columns:
          - name: id
            description: "Unique identifier for the vehicle"
          - name: registration_date
            description: "Date when the vehicle was registered"
          - name: make
            description: "Vehicle manufacturer"
          - name: model
            description: "Vehicle model"
          - name: bodytype
            description: "Type of vehicle body"
          - name: fuel
            description: "Type of fuel used by the vehicle"
          - name: data_source
            description: "Source of the data"
          - name: extraction_date
            description: "Date when the data was extracted"
            